### ISSUE TITLE
Great work! I would love to see it made runnable by anyone!

### ISSUE THREAD

**Issue by elliotmarks06** [kostyagomel44/restoration_photo#2]
I absolutely love the look of this project. I tried to run it, but it appears to be specifically designed to run on your machine. If you made this accessible for anyone to run, I could see it becoming a hugely popular tool among people like myself.

**Comment by kostyagomel44** [comment]
Hello. It's very nice to hear that.I am working in VScode, after cloning repo you should just write in congig file your telegram TOKEN and specify your paths everywhere.It is hard to say, where  exactly should they be specified, but you should base on errors from the code, there will be an indication where to change the directory.And of course add weights to the desired folders.I hope I helped you.22.06.2022, 02:13, "Elliot Marks" ***@***.***>:
I absolutely love the look of this project. I tried to run it, but it appears to be specifically designed to run on your machine. If you made this accessible for anyone to run, I could see it becoming a hugely popular tool among people like myself.

**Comment by elliotmarks06** [comment]
I'll try that. Thanks!
